#project euler #2
#7/13/2020
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
# answer = 4613732


old = 1
current = 2
newValue = 0
maxValue = 4000000

sum = 0
while (newValue < maxValue):
	if(current%2 == 0):
		sum+=current
	newValue = current + old
	old = current
	current = newValue
	print(current)
	
print("the total is: ", sum)