#!/usr/bin/perl
#use strict;
use warnings;

print "project Euler, problem two\n";
print "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ....\n By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.\n";

$sum = 0;
$b = 0;
$c = 0;

for( $a = 1; $a < 4000000; $a = $c + $b ){
    #print "TOP a = $a\n";
   #print "b = $b\n";
    #print "c = $c\n\n";
    if($a % 2 == 0 ){
        $sum+=$a;
    }
    $c = $b;
    $b = $a;
  
   # print "a = $a\n";
    #print "b = $b\n";
    #print "BOTTOM c = $c\n\n";
}
print "the total sum is $sum\n";
